server:
  port: 8080

spring:
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: 192.168.18.177:9300
  main:
    allow-bean-definition-overriding: true
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/movie?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml

